/**
 * UI Service - Bond Math User Interface
 *
 * Static site built with Astro + React, providing user interface for bond
 * calculation services. Authenticates users via Auth0 and communicates with
 * backend services through the Gateway API.
 *
 * @service ui
 * @type cloudflare-pages
 * @layer ui
 * @description User interface for bond math calculations - Astro static site with React islands
 * @owner platform-team
 * @external-routes /, /about, /day-count, /profile, /callback
 * @dependencies svc-gateway (via HTTPS)
 * @security-model auth0-oidc
 * @sla-tier high
 *
 * ## Architecture
 *
 * The UI is a static site generated by Astro with React islands for interactivity.
 * It deploys to Cloudflare Pages and communicates with backend services via HTTP.
 *
 * ### Authentication Flow
 *
 * 1. User authenticates via Auth0 Universal Login (PKCE flow)
 * 2. UI receives Auth0 access token and stores refresh token in localStorage
 * 3. UI sends bearer token to Gateway API in Authorization header
 * 4. Gateway verifies Auth0 token and mints internal JWT
 * 5. Gateway forwards request to appropriate service with internal JWT
 * 6. Response returned to UI and displayed to user
 *
 * ### Key Components
 *
 * - **API Client** (`lib/api/client.ts`) - Type-safe HTTP client for Gateway API
 * - **Auth Components** (`components/Auth*.tsx`) - Auth0 integration (login, logout, profile)
 * - **Calculator Components** (`components/*Calculator.tsx`) - Interactive calculators
 * - **Validation Utilities** (`lib/utils/validation.ts`) - Client-side input validation
 * - **Layout Components** (`layouts/*.astro`, `components/Header.astro`) - Shared page structure
 *
 * ### Technology Stack
 *
 * - **Astro 5.x** - Static site framework with islands architecture
 * - **React 18.x** - Interactive components (auth, calculators)
 * - **TailwindCSS 3.x** - Utility-first styling with custom design system
 * - **TypeScript 5.x** - Type safety throughout
 * - **Auth0 React SDK 2.x** - OAuth2/OIDC authentication
 *
 * ### Deployment
 *
 * - **Platform**: Cloudflare Pages
 * - **Build**: `astro build` generates static files in `dist/`
 * - **Deploy**: `wrangler pages deploy dist` or GitHub Actions
 * - **Environments**: development (localhost), preview (branch deployments), production
 *
 * ### Environment Variables
 *
 * Required (set in Cloudflare Pages):
 * - `PUBLIC_AUTH0_DOMAIN` - Auth0 tenant domain
 * - `PUBLIC_AUTH0_CLIENT_ID` - Auth0 SPA client ID
 * - `PUBLIC_AUTH0_AUDIENCE` - API audience identifier
 *
 * Optional:
 * - `PUBLIC_AUTH0_REDIRECT_URI` - Auth0 callback URL (defaults to `${origin}/callback`)
 * - `PUBLIC_API_BASE_URL` - API base URL (defaults to same origin in browser)
 * - `PUBLIC_SITE_URL` - Canonical site URL (defaults to production URL)
 */

// This file exists solely for AAC extraction - it defines the UI service metadata
// The actual UI functionality is implemented in components, pages, and lib files

export const SERVICE_METADATA = {
  id: 'ui',
  name: 'UI',
  type: 'cloudflare-pages',
  layer: 'presentation',
  description: 'User interface for bond math calculations',
  version: '2025.10',
} as const;
