@startuml
set separator none

skinparam {
  shadowing false
  arrowFontSize 15
  defaultTextAlignment center
  wrapWidth 100
  maxMessageSize 100
}
hide stereotype

skinparam rectangle<<_transparent>> {
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

skinparam rectangle<<1>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
rectangle "==Element" <<1>>

skinparam rectangle<<2>> {
  BackgroundColor #3178c6
  FontColor #ffffff
  BorderColor #22548a
}
rectangle "==API Gateway, TypeScript" <<2>>


@enduml